# Generated by Django 4.2.7 on 2024-05-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_name', models.CharField(max_length=200, verbose_name='Название QR-кода')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes', verbose_name='Изображение QR-кода')),
            ],
        ),
    ]
