name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/develop_for_deploy

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: d1g1tsdocker/streets_backend:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: 95.163.230.143
        username: root
        password: ${{ secrets.REMOTE_SSH_PASSWORD }}
        script: |
          cd /home/ubuntu/streets_backend/
          docker stop $(docker ps -a -q)
          docker rm $(docker ps -a -q)
          docker system prune -a -f
          docker-compose -f docker-compose.production.yml up -d
