name: CI

on:

  push:
    branches:
      - feature/docker_configuration # на время теста.

  # pull_request:
  #   types: [closed]
  #   branches:
  #     - develop

jobs:

  tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install black
          pip install -r requirements.txt

      # - name: run flake8
      #   run: flake8

      # - name: run black
      #   run: black --diff -S .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1


      - name: Run docker-compose
        run: |
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          echo DEBUG=${{ secrets.DEBUG }} >> .env
          echo ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo ENV_PATH=${{ secrets.ENV_PATH }} >> .env
          echo BASE_URL=${{ secrets.BASE_URL }} >> .env
          cd infra
          docker-compose -f docker-compose.workflows.yml up -d

      - name: Set migrations
        run: |
          sleep 5
          python streets_backend/manage.py makemigrations
          python streets_backend/manage.py migrate
      
  build_web:

    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 
      - name: Login to Docker
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2 
        with:
          push: true
          tags: d1g1tsdocker/streets_backend:latest

  clean_server:

    needs: 
      - build_web
    runs-on: ubuntu-latest
    steps:
    
      - name: Check connection to server
        uses: appleboy/ssh-action@master
        with:
          host: 95.163.230.143
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd infra
            sudo docker-compose -f $PWD/docker-compose.yml down -v --rmi all

  pull_web_image:

    runs-on: ubuntu-latest
    needs: clean_server
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 
      - name: Login to Docker 
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull d1g1tsdocker/streets_backend:latest
        run: docker pull d1g1tsdocker/streets_backend:latest
          
  deploy:

    needs: 
      - pull_web_image
    runs-on: ubuntu-latest
    steps:
      - name: Check connection to server
        uses: appleboy/ssh-action@master
        with:
          host: 95.163.230.143
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd infra
            sudo docker-compose -f $PWD/docker-compose.yml up -d --build
