name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/workflows

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: d1g1tsdocker/streets_backend:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: 95.163.230.143
        username: ubuntu
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: |
          docker-compose pull streets_backend
          docker-compose up -d